hla:
  federation_name: "RoboticsFed"
  federate_name: "ROS2Bridge"
  fom_file_path: "/home/vicen/ISDEFE/ros2_hla_ws/src/ROS2HLA_Bridge/fom/robotics.xml"
  pitch_jar_path: "/home/vicen/prti1516e/lib/prti1516e.jar"

# ROS2 -> HLA (We subscribe to ROS2 topic and Update Attribute Values in HLA)
ros_to_hla:
  - ros_topic: "/turtle1/pose"
    ros_type: "turtlesim.msg.Pose"
    hla_object_class: "Robot"
    hla_instance_name: "Turtle1"
    mapping:
      x: "positionX"
      y: "positionY"
      theta: "orientation"
  - ros_topic: "/turtle2/pose"
    ros_type: "turtlesim.msg.Pose"
    hla_object_class: "Robot"
    hla_instance_name: "Turtle2"
    mapping:
      x: "positionX"
      y: "positionY"
      theta: "orientation"

# HLA -> ROS2 (We receive Interaction/Attribute Update from HLA and Publish to ROS2 topic)
hla_to_ros:
  - ros_topic: "/turtle1/cmd_vel"
    ros_type: "geometry_msgs.msg.Twist"
    hla_interaction_class: "Control"
    filter_parameter: "robotName"
    filter_value: "Turtle1"
    mapping:
      linear.x: "linearVel"
      angular.z: "angularVel"
  - ros_topic: "/turtle2/cmd_vel"
    ros_type: "geometry_msgs.msg.Twist"
    hla_interaction_class: "Control"
    filter_parameter: "robotName"
    filter_value: "Turtle2"
    mapping:
      linear.x: "linearVel"
      angular.z: "angularVel"
