hla:
  federation_name: "RoboticsFed"
  federate_name: "ClientBridge_{{robot_name}}"
  fom_file_path: "/home/vicen/ISDEFE/ros2_hla_ws/src/ROS2HLA_Bridge/fom/robotics.xml"
  pitch_jar_path: "/home/vicen/prti1516e/lib/prti1516e.jar"

# ROS2 -> HLA (Client sends commands)
ros_to_hla:
  - ros_topic: "/{{robot_name}}/cmd_vel"
    ros_type: "geometry_msgs.msg.Twist"
    hla_interaction_class: "Control"
    mapping:
      linear.x: "linearVel"
      angular.z: "angularVel"
    fixed_parameters:
      robotName: "{{robot_name}}"

# HLA -> ROS2 (Client receives pose)
hla_to_ros:
  - ros_topic: "/{{robot_name}}/pose"
    ros_type: "turtlesim.msg.Pose"
    hla_object_class: "Robot"
    hla_instance_name: "{{robot_name}}"
    mapping:
      x: "positionX"
      y: "positionY"
      theta: "orientation"
