federation_name: "GazeboHlaFed"
federate_name: "ClientBridge_1"
fom_name: "UniversalRosFom"
time:
  mode: "hla_slave"
  step: 0.01
  lookahead: 0.01
  publish_clock: false
nodes:
  robot_1:
    object_class: "Robot"
    attributes:
      pose:
        ros_topic: "/robot_1/odometry"
        ros_type: "nav_msgs.msg.Odometry"
        direction: "hla_to_ros2"
      cmd_vel:
        ros_topic: "/robot_1/cmd_vel"
        ros_type: "geometry_msgs.msg.Twist"
        direction: "ros2_to_hla"
