federation_name: "GazeboHlaFed"
federate_name: "ClientBridge_2"
fom_name: "UniversalRosFom"
time:
  mode: "hla_slave"
  step: 0.01
  lookahead: 0.01
  publish_clock: false
nodes:
  robot_2:
    object_class: "Robot"
    attributes:
      pose:
        ros_topic: "/robot_2/pose"
        ros_type: "geometry_msgs.msg.Pose"
        direction: "hla_to_ros2"
      cmd_vel:
        ros_topic: "/robot_2/cmd_vel"
        ros_type: "geometry_msgs.msg.Twist"
        direction: "ros2_to_hla"
