federation_name: "RosHlaFed"
fom_name: "UniversalRosFom"
time:
  mode: "hla_master" # Options: "hla_master", "ros_master", "none"
  step: 0.1 # Time step in seconds
  lookahead: 0.1 # Lookahead for regulation
nodes:
  turtlesim:
    object_class: "Turtlesim"
    attributes:
      pose:
        ros_topic: "/turtle1/pose"
        ros_type: "turtlesim.msg.Pose"
        direction: "ros2_to_hla"
      cmd_vel:
        ros_topic: "/turtle1/cmd_vel"
        ros_type: "geometry_msgs.msg.Twist"
        direction: "hla_to_ros2"
